services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
      DATABASE_URL: sqlite:///instance/ai_market_matching.db
    volumes:
      - .:/app:delegated
      - ./instance:/app/instance:delegated
      - ./uploads:/app/uploads:delegated
    restart: unless-stopped
